name: mad_project
description: A new Flutter project.

version: 0.0.1+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # More flexible SDK constraint

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7  # or latest version
  english_words: ^4.0.0
  cupertino_icons: ^1.0.2
  provider: ^6.1.1  # Updated to a newer version
  intl: ^0.18.0  # Add this line
  # Remove carousel_slider package as we're using a custom implementation
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1  # Updated to a more compatible version

flutter:
  uses-material-design: true
  assets:
    - assets/images/findworkd.svg
    - assets/images/findwork.svg
    - assets/images/apply_job.png
    - assets/images/hire_worker.png
    - assets/images/job_posting.png
    - assets/images/post_proficiency.png
    - assets/images/electrician.png
    - assets/images/plumber.png
    - assets/images/google_logo.png
    - assets/images/microsoft_logo.png
    - assets/images/auth_vector.png
    
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato-Regular.ttf
        - asset: assets/fonts/Lato-Medium.ttf
        - asset: assets/fonts/Lato-Light.ttf
        - asset: assets/fonts/Lato-Semibold.ttf
        - asset: assets/fonts/Lato-Bold.ttf
        - asset: assets/fonts/Lato-Black.ttf
        - asset: assets/fonts/Lato-Italic.ttf
        - asset: assets/fonts/Lato-BoldItalic.ttf
        - asset: assets/fonts/Lato-BlackItalic.ttf
        - asset: assets/fonts/Lato-LightItalic.ttf
        - asset: assets/fonts/Lato-MediumItalic.ttf
        - asset: assets/fonts/Lato-SemiboldItalic.ttf
        - asset: assets/fonts/Lato-Thin.ttf
        - asset: assets/fonts/Lato-ThinItalic.ttf
        - asset: assets/fonts/Lato-Heavy.ttf
        - asset: assets/fonts/Lato-HeavyItalic.ttf
        - asset: assets/fonts/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/Lato-Italic.ttf
          style: italic
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf

