// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB2C-kgl14dNkrOuKf-a54VznnoNPFIdk',
    appId: '1:412890681824:web:0d3d5e963f6f084b839b85',
    messagingSenderId: '412890681824',
    projectId: 'findwork-app',
    authDomain: 'findwork-app.firebaseapp.com',
    storageBucket: 'findwork-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWZHf-Se1FNYrUExd_hBuTHdi63cg1PxA',
    appId: '1:412890681824:android:28685156eb7c1840839b85',
    messagingSenderId: '412890681824',
    projectId: 'findwork-app',
    storageBucket: 'findwork-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMiKNoOrGbrRx3_II13Lr8jQ7kg82PuIc',
    appId: '1:412890681824:ios:a9aebd9b745d907b839b85',
    messagingSenderId: '412890681824',
    projectId: 'findwork-app',
    storageBucket: 'findwork-app.firebasestorage.app',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMiKNoOrGbrRx3_II13Lr8jQ7kg82PuIc',
    appId: '1:412890681824:ios:a9aebd9b745d907b839b85',
    messagingSenderId: '412890681824',
    projectId: 'findwork-app',
    storageBucket: 'findwork-app.firebasestorage.app',
    iosBundleId: 'com.example.madProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB2C-kgl14dNkrOuKf-a54VznnoNPFIdk',
    appId: '1:412890681824:web:ec8228ffab2ac05d839b85',
    messagingSenderId: '412890681824',
    projectId: 'findwork-app',
    authDomain: 'findwork-app.firebaseapp.com',
    storageBucket: 'findwork-app.firebasestorage.app',
  );
}
